### PR TITLE
Switch docker push to be triggered on new release

### PR DESCRIPTION
**Pull request by greenhat**

### CODE REVIEW

**Comment by reqlez** [comment]
After test is successful, don't forget there are 3 places with username/reponame in that action. Just heads up  ;-)

**Review by reqlez — APPROVED** [review]

**Comment by reqlez** [comment]
Based on this run here, it's now working properly:
https://github.com/ergoplatform/oracle-core/actions/runs/6105865742

I changed it here to ergoplatform/oracle-core DockerHub repo now, that repo just needs to be created before we run this on release. @kushti heads up, and also set proper DOCKERHUB_USERNAME  DOCKERHUB_TOKEN for ergoplatform account.

Otherwise, LGTM after the above 2 tasks are complete.

**Comment by greenhat** [comment]
@reqlez Great job! Thank you very much!

**Comment by reqlez** [comment]
> @reqlez Great job! Thank you very much!

Happy to help! Now just waiting for @kushti to do his thing and we g2g!

**Comment by reqlez** [comment]
@kushti any luck setting this up?

**Pull request merged**
